task:
  name: FreeBSD (shortest)
  freebsd_instance:
    matrix:
      image_family: freebsd-14-0-snap
  install_script: pkg install -y fontconfig pkgconf rust libxkbcommon
  script: |
    cargo build --release
