#! /usr/bin/env python3
from os import environ, makedirs
import re

pkgver = environ.get('PKGVER')
if not pkgver:
  print('::error ::PKGREL is required but missing')
  exit(1)

maintainer = "# Maintainer: Folke H. 'joru' Gleumes <folke-aur@gleumes.org>"
opening = maintainer + '\n# This file is automatically generated. Do not edit.\n'

print('Generating PKGBUILD for kickoff...')
makedirs('./pkgbuild/kickoff-git', exist_ok=True)
with open('./pkgbuild/kickoff-git/PKGBUILD', 'w') as pkgbuild:
  content = opening + '\n'
  content += f'pkgver={pkgver}\n'
  content += open('./template/kickoff-git/PKGBUILD').read() + '\n'
  pkgbuild.write(content)
